# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2931966609ff7b76eb6b46851508279c3af387ce9fa146c560a5ad9ae91ea6b721d9a37f962cfe3ae38595f74f0d8d50725558c57adee459c03802fa9e9692e

test:
  secret_key_base: 300f1d78176c4a6935be944f5f2c604f251e75b5d8d31d2777e8b9b3f0bc1f3246d6ec1dc3a85993566a17775fcd3a0a2ec08491a0920b1510ce5972b70a171c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
